### ISSUE TITLE
Price should not be calculated with data sent from client

### ISSUE THREAD

**Issue by jminardi** [testdrivenio/flask-vue-stripe#1]
https://github.com/testdrivenio/flask-vue-stripe/blob/54dd53c77cb1633ffc126b2532466f5b42ed4aa1/server/app.py#L106

A clever client will be able to set the price to whatever they want.

**Comment by mjhea0** [comment]
Yes, you should verify the price in the backend before generating the charge.

1. Get the book info from the database
2. Verify that the book price (from the db) is the same as the price in the POST request
